### ISSUE TITLE
请问下这个代码字体是什么

### ISSUE THREAD

**Issue by EthanLin-TWer** [LearnShare/Learning-Markdown#6]
链接在这里：http://xianbai.me/learn-md/article/extension/code-blocks-and-highlighting.html 我直接贴图吧

![image](https://cloud.githubusercontent.com/assets/11895199/16541091/94308bf8-40ac-11e6-8e0e-dbf7fe2e2703.png)

我苦寻这个字体已久:) 麻烦告知一下啦谢谢~

**Comment by ThomasChan** [comment]
![image](https://cloud.githubusercontent.com/assets/5715335/16550232/71f032bc-41da-11e6-916a-f16d00efe505.png)
是这个吧？MONACO

**Comment by EthanLin-TWer** [comment]
啊谢谢。

![image](https://cloud.githubusercontent.com/assets/11895199/16551232/5c1bdbc2-41e8-11e6-9df3-b94849bf0278.png)

就是不知道我的怎么这么丑……看起来更宽松。还是谢谢啦
